//
//  main.m
//  Problem2
//
//  Created by James Hodgkinson on 28/03/2014.
//  Copyright (c) 2014 James Hodgkinson. All rights reserved.
//
/*
 Problem 2
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 
 
 Answer:
 4613732
 
 */


#import <Foundation/Foundation.h>

int main(int argc, const char * argv[])
{

    @autoreleasepool {
        
        int x = 0;
        int y = 1;
        int z = 0;
        int sumN = 0;
        while( z < 4000000 )
        {
            z = x + y;
            x = y;
            y = z;
            if( z % 2 == 0 )
                sumN += z;

        }
        NSLog(  @"The sum is: %d", sumN );
        
        
    }
    return 0;
}

